apiVersion: v1
kind: Service
metadata:
  name: icloudphoto-svc
  namespace: icloudphoto
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: icloudphoto-app
  type: LoadBalancer
  loadBalancerIP: 10.0.10.27
  ports:
    - name: icloudphoto-port
      protocol: TCP
      port: 80
      targetPort: 5000
  externalIPs:
  - 10.0.10.27