name: build and push docker image image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 6'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
      
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Run Buildx
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t tcousin/icloud-photo-display:latest -t tcousin/icloud-photo-display:$GITHUB_SHA --push . 
